### PR TITLE
nonce bug fix

### LINKED ISSUE #70: [BUG] Intermittent failures on log in, due to undefined nonce bug.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using `express-api` example for local development, running the command:
```
$ yarn express-api serve
```
Occasionally, the log in attempt fails with the same `Cannot read properties of undefined (reading 'nonce')` message that was in #54 

This appears to be the same bug, but no longer reliablely reproducible. I've noticed it ~ 1 in every 10 logins, and @anukritidata ran into it once.

The changes in recent PRs seem to have altered the failure from every other login to much rarer but still present, and the changes may have a clue as to where the problem lies.

### Expected Behavior

No failures from an undefined nonce.

### Steps To Reproduce

On the main branch, using the `express-api` example, every once in a while, the nonce will be undefined.

### Anything else?

I have a feeling this will be a tricky one. It may be worth going back in time to PR #64 or earlier when this happened consistently.

### PR DESCRIPTION
**Pull request by franklovefrank**
# Description

fixes bug described here https://github.com/spruceid/ssx/issues/70

# Type

- [x] Bug fix (non-breaking change which fixes an issue)

# Diligence Checklist

- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

### CODE REVIEW

File: packages/ssx-server-middleware/src/express/endpoints.ts [hunk 1]
```diff
@@ -86,7 +87,7 @@ const ssxEndpoints = (
       req.session.daoLogin = session.daoLogin;
       req.session.ens = session.ens;
       req.session.lens = session.lens;
-
+      req.session.save(() => res.status(200).json({ ...req.session }));
       res.status(200).json({ ...req.session });
```
Comment (Juliano1612) [inline packages/ssx-server-middleware/src/express/endpoints.ts]:
```suggestion
```
It is already being done on line 90

**Review by Juliano1612 — CHANGES_REQUESTED** [review]

**Review by w4ll3 — COMMENTED** [review]
Just awaiting for requested changes

**Review by Juliano1612 — APPROVED** [review]

**Review by w4ll3 — APPROVED** [review]
